### ISSUE TITLE
How to include country code while sending sms

### ISSUE THREAD

**Issue by vkeziah** [messagebird/ruby-rest-api#7] opened 2016-03-28 05:19 UTC
can you please let me know how to include country code while sending sms , I tried include country code but it does not work for me , see the following 

@message_bird_client.message_create('FromMe', '+919440443344', 'Hello World', :reference => 'MyReference')

**Comment by samwierema** [comment] 2016-03-29 09:18
Hi @vkeziah, 

Where would you like to include the country code exactly? In the `originator` parameter, or somewhere else?

**Comment by vkeziah** [comment] 2016-03-29 10:02
see my above example I included my country code +91 along with my mobile number, is it wrong ? also I tried to included country code in originator parameter, but unable to receive sms got an error

**Comment by samwierema** [comment] 2016-03-29 10:05
The code, as you pasted it, should work. Are you receiving an error, and if so, which error? And, to double-check: are you using a `live` or a `test` key?

**Comment by vkeziah** [comment] 2016-03-29 10:25
See the following is the error message I have been facing

client.message_create('Ratnakar', '+91 8008286288', 'Hello World', :reference => 'MyReference')

MessageBird::ErrorException: MessageBird::ErrorException
from /home/ratnakar/.rvm/gems/ruby-2.2.2@fetchadmin/gems/messagebird-rest-1.3.1/lib/messagebird/client.rb:59:in `request'

**Comment by samwierema** [comment] 2016-03-29 10:45
Ok, can you tell me what is in the `MessageBird::ErrorException`?

**Comment by vkeziah** [comment] 2016-03-29 10:46
That is the complete error message

**Comment by samwierema** [comment] 2016-03-29 10:50
Can you try this code and tell me what the output is:

```ruby
begin
  client.message_create('Ratnakar', '+91 8008286288', 'Hello World', :reference => 'MyReference')
rescue MessageBird::ErrorException => ex
  puts
  puts 'An error occured while requesting a Message object:'
  puts

  ex.errors.each do |error|
    puts "  code        : #{error.code}"
    puts "  description : #{error.description}"
    puts "  parameter   : #{error.parameter}"
    puts
  end
end
```

Of course with all your other supporting code.

**Comment by vkeziah** [comment] 2016-03-29 11:01
Now I no error however there is success status , but really I did not receive any sms on my mobile :(

See this 

"items"=>[#<MessageBird::Recipient:0x00000007810f40 @recipient=918008286288, @status="sent", @statusDatetime=2016-03-29 10:55:38 +0000>]

**Comment by samwierema** [comment] 2016-03-29 11:09
I can confirm your request has reached our API, but I've found that the message is not sent due to a different issue. I've escalated your request to our tech support desk and will get back to you when they have an answer.

**Comment by vkeziah** [comment] 2016-03-29 11:17
Ok Thanks @samwierema

**Comment by samwierema** [comment] 2016-03-29 11:35
We've found that the number: `+918008286288` appears on India's [Do Not Disturb list](http://dndcheck.in/). As such, it can not receive messages. This restriction, as well as other restrictions for India, can be found in our knowledge base: http://support.messagebird.com/hc/en-us/articles/203780362-India.

As the code works from a technical point-of-view, I'll close this issue for now. Please let us know if you have any further questions and/or feedback.

**Closed by samwierema** 2016-03-29 11:35 UTC

**Comment by karanveer14** [comment] 2018-05-15 06:13
Someone please guide me can can i use the test credit of MessageBird to send live messages
