### ISSUE TITLE
Send messages to short numbers

### ISSUE THREAD

**Issue by amarildolucas** [messagebird/ruby-rest-api#24] opened 2018-12-28 19:07 UTC
Hi, i really like messagebird-rest ruby gem.

I want to know if it's possible to send message to short numbers. In my case these numbers do operations after receiving these messages.

**For example: 45100**

But i got an error, so i think because is the length of the phone number:

`MessageBird::ErrorException (MessageBird::ErrorException)`

Thanks.

**Comment by marcelcorso** [comment] 2018-12-29 20:57
Hey Amarildo. 

It should work. 

Did you try to look "inside" the exception? `MessageBird::ErrorException#errors` is a list 

like this
https://github.com/messagebird/ruby-rest-api/blob/d9d0855eb97662d8f9910d406d714942e3211138/examples/message_create.rb#L36

maybe you can find the root cause. Let us know!

**Comment by amarildolucas** [comment] 2019-01-09 12:00
Hi @marcelcorso thank you for the help.

This is the error that i get in the exception block:
```
An error occured while requesting a Message object:
  code        : 9
  description : no (correct) recipients found
  parameter   : recipient
```

And this is the message that i'm trying to send:
```
client.message_create(
  'KAMBA',
  '45100', # @operator_recharge_phone_number,
  'message', # @message,
        reference: 'reference' # "tv-recharge-#{id}"
)
```

**Comment by marcelcorso** [comment] 2019-01-10 14:02
Opa @amarildolucas. 
I asked some colleagues and they told me that there is a intentional restriction on sending SMS to shortcodes. 
First shortcodes are not globally unique: they are agreed in a country by country or even only work operators. So it's hard for messagebird to know to exactly where to send them. 

Also sometimes when sending SMS to shortcodes you have implied costs. Who should pay for those costs? It's not very easy to come up with a system that would solve that in a good way. 

So this is not an SDK bug so I'm closing this. If you want to know more please talk to our support people at https://support.messagebird.com/hc/en-us!

**Closed by marcelcorso** 2019-01-10 14:02 UTC
